version: "3.7"

services:
  transcription-woker:
    build: .
    deploy:
      replicas: 1
    environment:
      GLADIA_API_KEY: ---
    volumes:
      - ./src:/usr/src/app
    command: npm run dev
    networks:
      - mnemosine
networks:
  mnemosine:
    name: mnemosine
    external: true