version: "3.7"

services:
  transcription-woker:
    build: .
    deploy:
      replicas: 1
    environment:
      REPLICATE_API_TOKEN: 6ea8b76af81c7a8fa94c17a0022f969fe4beed34  
    volumes:
      - ./src:/usr/src/app
    command: npm run dev
    networks:
      - mnemosine
networks:
  mnemosine:
    name: mnemosine
    external: true